<a href="https://colab.research.google.com/github/diogenesjusto/FIAP/blob/master/Gradua%C3%A7%C3%A3o/2026/2TSCPV_20260924_P1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/diogenesjusto/FIAP/refs/heads/master/Gradua%C3%A7%C3%A3o/dados/dados_arvore_titanic.csv")

In [3]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:

pd.crosstab(df['Survived'], df['Sex'], margins=True)

Sex       female  male  All
Survived
0             81   468  549
1            233   109  342
All          314   577  891

In [9]:
# Probabilidade de sobrevivência de um passageiro embarcado no titanic
# P = x/T
P_sobrevivencia = 342/891
P_sobrevivencia

0.3838383838383838

In [11]:
# Pela 2.a Axioma de probabilidades, calculamos a P_morte
P_morte = 1 - P_sobrevivencia
P_morte

0.6161616161616161

In [12]:
# Probabilidade de um passageiro ser do gênero feminino
P_mulher = 314/891
P_mulher

0.35241301907968575

In [14]:
# Probabilidades de sobrevivência de mulheres e homens => P(A|B) = P(A U B)/PB
P_sob_mulher = 233/314
P_sob_mulher

0.7420382165605095

In [15]:
P_sob_homens = 109/577
P_sob_homens

0.18890814558058924

In [16]:
# Se fizermos com classe (Pclass), ao invés de gênero (Sex)
pd.crosstab(df['Survived'], df['Pclass'], margins=True)

Pclass      1    2    3  All
Survived
0          80   97  372  549
1         136   87  119  342
All       216  184  491  891