<a href="https://colab.research.google.com/github/diogenesjusto/FIAP/blob/master/Gradua%C3%A7%C3%A3o/2025/20250930_Exercicio_Analise_Investimentos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import yfinance as yf

In [26]:
ticker = ['USDBRL=X','^BVSP']

In [27]:
# intraday
dyf = yf.download(ticker, period="60d", interval="1d")

/tmp/ipython-input-432140514.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  dyf = yf.download(ticker, period="60d", interval="1d")
[*********************100%***********************]  2 of 2 completed

In [28]:
dyf['Close']

Ticker      USDBRL=X          ^BVSP
Date
2025-07-09       NaN  137481.000000
2025-07-10    5.5818  136743.000000
2025-07-11    5.5311  136187.000000
2025-07-14    5.5719  135299.000000
2025-07-15    5.5870  135250.000000
...              ...            ...
2025-09-25    5.3299  145306.000000
2025-09-26    5.3637  145447.000000
2025-09-29       NaN  146337.000000
2025-09-30       NaN  146237.015625
2025-10-01    5.3195            NaN

[61 rows x 2 columns]

In [29]:
dyf['Close'].dropna().corr()

Ticker    USDBRL=X    ^BVSP
Ticker
USDBRL=X   1.00000 -0.85429
^BVSP     -0.85429  1.00000