<a href="https://colab.research.google.com/github/diogenesjusto/FIAP/blob/master/MBAIA/14DTSR_Aula3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dados "temporais" - Time Series

In [30]:
# Dados do Itau Unibanco PIBIU
# + dados de tráfego da ABCR: https://melhoresrodovias.org.br/
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [31]:
# 2. Carga de dados
df = pd.read_csv("https://raw.githubusercontent.com/diogenesjusto/FIAP/master/SHIFT/Data/pib.csv")
df

,Unnamed: 0,ANO_MES,PIB,BRL,BRP,BRT,SLP,SPP,SPT,PRL,...,PIBi3,PIBi4,PIBi5,PIBi6,PIBi7,PIBi8,PIBi9,PIBi10,PIBi11,PIBi12
0,1,jan/04,103.09,109.19,108.67,109.08,102.84,114.27,105.38,127.49,...,106.27,104.52,102.59,102.24,99.96,101.93,101.17,101.70,100.03,100.00
1,2,fev/04,102.05,95.65,104.52,97.63,90.76,109.83,94.99,96.60,...,104.10,106.27,104.52,102.59,102.24,99.96,101.93,101.17,101.70,100.03
2,3,mar/04,110.43,91.69,125.53,99.26,89.78,133.24,99.43,83.79,...,103.91,104.10,106.27,104.52,102.59,102.24,99.96,101.93,101.17,101.70
3,4,abr/04,106.77,95.36,118.34,100.49,94.58,123.55,101.02,91.79,...,103.09,103.91,104.10,106.27,104.52,102.59,102.24,99.96,101.93,101.17
4,5,mai/04,108.08,92.47,121.49,98.96,91.34,128.32,99.55,85.73,...,102.05,103.09,103.91,104.10,106.27,104.52,102.59,102.24,99.96,101.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,134,fev/15,144.42,147.35,133.73,143.57,147.81,148.96,147.54,157.30,...,151.46,156.65,154.04,154.75,154.34,148.92,154.49,150.92,151.44,148.92
134,135,mar/15,151.68,149.64,163.27,152.09,154.87,179.07,159.56,147.28,...,150.70,151.46,156.65,154.04,154.75,154.34,148.92,154.49,150.92,151.44
135,136,abr/15,147.03,153.81,149.93,152.28,161.21,164.74,161.16,162.21,...,149.51,150.70,151.46,156.65,154.04,154.75,154.34,148.92,154.49,150.92
136,137,mai/15,148.94,149.66,153.03,149.82,157.03,169.39,158.76,149.06,...,144.42,149.51,150.70,151.46,156.65,154.04,154.75,154.34,148.92,154.49
137,138,jun/15,147.37,146.13,147.98,145.84,152.96,162.92,153.86,144.14,...,151.68,144.42,149.51,150.70,151.46,156.65,154.04,154.75,154.34,148.92

In [32]:
# 2. Construção das variáveis com Lag
df['PIBi1_'] = df['PIB'].shift(1)
df['PIBi2_'] = df['PIB'].shift(2)

In [33]:
# 3. Separação de treino e teste
# Dados temporais(série temporal) => amostra por janela temporal
treino = df.iloc[0:132]
teste = df.iloc[132:138]

In [47]:
#4. Regressão Linear
Y_treino = treino.iloc[:,[2]]

#X = ['BRP'] # RLS, exógena BRP

#X = ['PIBi1', 'PIBi2'] # AR2, modelo autoregressivo de ordem 2
#X = ['PIBi1', 'PIBi2','PIBi3'] # AR3, modelo autoregressivo de ordem 3
#X = ['PIBi1', 'PIBi2','PIBi3', 'PIBi4'] # AR4, modelo autoregressivo de ordem 4
#X = ['PIBi1', 'PIBi2','PIBi3', 'PIBi4', 'PIBi12'] # AR4, modelo autoregressivo de ordem 4+ajuste sazonal-> tendência

X = ['BRP', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11'] # Modelo Multivariado com tratamento de sazonalidade através de dummies
X_treino = treino.loc[:,X]

mod = LinearRegression()
mod.fit(X = X_treino, y = Y_treino)

print(mod.score(X_treino, Y_treino))

0.947781027716414

In [48]:
print(mod.coef_) # coef angular ou a
print(mod.intercept_) # coef linear ou b

[[ 0.87652012  2.01414759  2.5069761  -7.36083261 -4.16662299 -4.79808918
  -0.76167701 -3.21330987 -6.6408769  -5.08102737 -7.74682554 -3.42193813]]
[11.70329027]

In [49]:
#5. Previsão em teste
X_teste = teste.loc[:,X]
Y_prev = mod.predict(X_teste)

Y_prev
Y_real = teste.iloc[:,[2]]
Erro = Y_prev - Y_real
abs(Erro).mean()

PIB    7.676173
dtype: float64